---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}
  namespace: default
  labels:
    app: test-api
  annotations:
    konghq.com/protocol: https
    konghq.com/plugins: kong-rate-limiting-cluster-plugin, testcenter-api-openid-connect-plugin 
spec:
  type: {{ .Values.service.type }}
  selector:
    app: test-api
    {{- include "myapp.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000