# Rendered from helm
# helm template test-api ./ | tee rendered.yaml
---
# Source: myapp/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-api-cfgmap
  labels:
    helm.sh/chart: myapp-0.1.0
    app.kubernetes.io/name: test-api
    app.kubernetes.io/instance: test-api
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  # file-like keys
  test-api.config: |
    NODE_ENV=dev
    APP_LOG=./logs/capi.log
    LOG_LEVEL=debug
    LOG_REQUEST=true
    HTTPS_PORT=9000
    BAPI_HOST=test.abcd.net
    BAPI_BASE_URL=/api-rest/v1
    ENDPOINT_LOGON_INFO=/enterprise/userPreference
    ENDPOINT_TDSSA=/tdp/tdssa
    ENDPOINT_TDP=/tdp
    ENDPOINT_DCF=/dcf
    ENDPOINT_COUNTRIES=/country
    ENDPOINT_ORGANIZATION=/organization
    ENDPOINT_DASHBOARD=/dashboard
    ENDPOINT_USER=/user
    ENDPOINT_MODULEACCESS=/moduleAccess
    ENDPOINT_WHEREABOUTS=/whereaboutsNG
    ENDPOINT_ATHLETE=/customer
    SECURE_PASS_PHRASE=secretSupermanPassPhrase
    ENDPOINT_TEST=/testing
    ENDPOINT_TESTING_ORDER=/testingOrder
    DEFAULT_USER_LOCALE=en
    TDP_USER_ACTIVE_SINCE_MILLISECONDS=300000
---
# Source: myapp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-api
  namespace: default
  labels:
    app: test-api
  annotations:
    konghq.com/protocol: https
    konghq.com/plugins: kong-rate-limiting-cluster-plugin, testcenter-api-openid-connect-plugin 
spec:
  type: NodePort
  selector:
    app: test-api
    app.kubernetes.io/name: test-api
    app.kubernetes.io/instance: test-api
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8000
---
# Source: myapp/templates/kongplugin-crd.yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: test-oidc-plugin
  namespace: default
config:
  upstream_headers_claims:
  - adams_useraccount_id
  - preferred_username
  - given_name
  - family_name
  - email
  upstream_headers_names:
  - X-SSO-AdamsUserId
  - X-SSO-Username
  - X-SSO-Firstname
  - X-SSO-Lastname
  - X-SSO-Email
  session_secret: secretSupermanSessionSecret
  login_methods:
  - authorization_code
  auth_methods:
  - session
  password_param_type:
  - header
  - query
  - body
  session_storage: redis
  refresh_tokens: true
  upstream_access_token_header: authorization:bearer
  verify_claims: true
  id_token_param_type:
  - header
  - query
  - body
  session_redis_port: 6379
  session_strategy: default
  session_cookie_samesite: Lax
  session_cookie_httponly: true
  issuer: https://sso.abcd.net/auth/realms/test/.well-known/openid-configuration
  cache_tokens: true
  run_on_preflight: true
  client_auth:
  - client_secret_basic
  authorization_cookie_path: "/"
  response_type:
  - code
  session_redis_host: kong-redis-master
  session_redis_auth: secretSupermanRedisAuth
  login_action: redirect
  refresh_token_param_type:
  - header
  - query
  - body
  authorization_cookie_samesite: 'off'
  session_redis_ssl_verify: false
  client_secret:
  - secretSupermanPassPhrase
  login_tokens:
  - id_token
  ssl_verify: false
  authorization_cookie_name: authorization
  session_cookie_lifetime: 3600
  verify_nonce: true
  response_mode: query
  reverify: false
  session_cookie_path: "/"
  bearer_token_param_type:
  - header
  - query
  - body
  cache_user_info: true
  rediscovery_lifetime: 30
  verify_signature: true
  forbidden_destroy_session: true
  client_id:
  - secretSupermanClientId
  client_credentials_param_type:
  - header
  - query
  - body
  session_cookie_renew: 600
  session_cookie_name: session
  session_redis_prefix: sessions
  client_arg: client_id
  scopes:
  - openid
  authorization_cookie_httponly: true
  logout_methods:
  - POST
  - DELETE
plugin: openid-connect
